// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Enum_DistanceUnit
{
	KILOMETER("2149fd31-261f-4b71-91e1-c1459daa5146"),
	STATUTE_MILE("b27d9a8c-1369-4293-b420-a8422bcb8ce3"),
	NAUTICAL_MILE("46cccdd3-9949-40f7-8cfe-d53d5980649e");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
