// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("d3390207-e9a5-42cd-a0a6-8d3bd4a7578b"),
	denied("a8e97fab-276a-49dc-adaa-11a4d665d279"),
	limited("c7f4ab5a-9cee-4c63-b7a8-14bcc0838969"),
	granted("6d8c3777-b5e0-4ee5-9976-0775336031a4"),
	blocked("6241b3d3-2a6e-4903-9292-cf7aaa29ca4f");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
