// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("3673666c-1711-4fbd-9c99-3ec7ef76c4db"),
	low("fe48e600-a98f-49e7-aaec-1f1fe1f2005e"),
	medium("18bf6478-89ce-4570-849c-b1284b6d6fd9"),
	high("2647a7cb-3abc-4144-afc2-6838a7f2e0bc"),
	custom("ea2715a3-4831-4469-8d2d-fabcd806e180");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
